server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost/turntablegame?useUnicode=true&allowMultiQueries=true&chaeacterEncoding=UTF-8&serverTimeZone=UTC&useSSL=false
    username: root
    password: admin
    #关于druid的配置
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      # 配置监控统计拦截的 Filter，去掉后监控界面 SQL 无法统计，wall 用于防火墙
      filters: stat,wall,slf4j
      filter:
        stat:
          slow-sql-millis: 1000 #超过1秒是慢sql
          log-slow-sql: true
          enabled: true
          db-type: mysql
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        url-pattern: /druid/*
        reset-enable: false
        #        allow: 127.0.0.1
        login-username: druid
        login-password: druid
  data:
    redis:
      host: 192.168.0.239
      port: 6379
      password: Lta102103,./



#logging:
#  level:
#    com.laituo.schoolStu.mapper: debug

#打印记录
#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl