
#============================================================================
# 线程池 setting
#============================================================================
executor:
  corePoolSize: 0 #核心线程数量，0默认cpu核心数量
  maxPoolSize: 0 #最大线程数量，0默认cpu核心数量两倍
  keepAliveSeconds: 60 #空闲线程存活时间，默认60秒
  queueCapacity: 10 #最大队列数，默认10
  allowCoreThreadTimeout: false #是否允许核心线程超时，默认否
